export interface Voice {
    id: string;
    name: string;
    style: string;
    description: string;
    color: string;
    colorEnd: string;
}

export const voices: Voice[] = [
    {
        id: "adam",
        name: "Adam",
        style: "Dominant, Firm",
        description: "A bright tenor pitch that immediately cuts through",
        color: "#22c55e",
        colorEnd: "#16a34a",
    },
    {
        id: "alice",
        name: "Alice",
        style: "Clear, Engaging Educator",
        description: "Clear and engaging, friendly woman with warmth",
        color: "#3b82f6",
        colorEnd: "#2563eb",
    },
    {
        id: "bill",
        name: "Bill",
        style: "Wise, Mature, Balanced",
        description: "Friendly and comforting voice ready to assist",
        color: "#22c55e",
        colorEnd: "#16a34a",
    },
    {
        id: "brian",
        name: "Brian",
        style: "Deep, Resonant and Comforting",
        description: "Middle-aged man with a resonant and calming tone",
        color: "#6366f1",
        colorEnd: "#4f46e5",
    },
    {
        id: "callum",
        name: "Callum",
        style: "Husky Trickster",
        description: "Deceptively gravelly, yet unsettling edge",
        color: "#8b5cf6",
        colorEnd: "#7c3aed",
    },
    {
        id: "charlie",
        name: "Charlie",
        style: "Deep, Confident, Energetic",
        description: "A young Australian male with a confident demeanor",
        color: "#ef4444",
        colorEnd: "#dc2626",
    },
    {
        id: "chris",
        name: "Chris",
        style: "Charming, Down-to-Earth",
        description: "Natural and real, this down-to-earth voice connects",
        color: "#f97316",
        colorEnd: "#ea580c",
    },
    {
        id: "daniel",
        name: "Daniel",
        style: "Steady Broadcaster",
        description: "A strong voice perfect for delivering authoritative content",
        color: "#6366f1",
        colorEnd: "#4f46e5",
    },
    {
        id: "eric",
        name: "Eric",
        style: "Smooth, Trustworthy",
        description: "A smooth tenor pitch from a man in his prime",
        color: "#3b82f6",
        colorEnd: "#2563eb",
    },
    {
        id: "george",
        name: "George",
        style: "Warm, Captivating Storyteller",
        description: "Warm resonance that instantly captivates listeners",
        color: "#22c55e",
        colorEnd: "#16a34a",
    },
    {
        id: "harry",
        name: "Harry",
        style: "Fierce Warrior",
        description: "An animated warrior ready to charge into battle",
        color: "#ef4444",
        colorEnd: "#dc2626",
    },
    {
        id: "jessica",
        name: "Jessica",
        style: "Playful, Bright, Warm",
        description: "Young and popular, this playful American voice shines",
        color: "#ec4899",
        colorEnd: "#db2777",
    },
    {
        id: "laura",
        name: "Laura",
        style: "Enthusiast, Quirky Attitude",
        description: "This young adult female voice delivers personality",
        color: "#f97316",
        colorEnd: "#ea580c",
    },
    {
        id: "liam",
        name: "Liam",
        style: "Energetic, Social Media Creator",
        description: "A young adult with energy and warmth",
        color: "#22c55e",
        colorEnd: "#16a34a",
    },
    {
        id: "lily",
        name: "Lily",
        style: "Velvety Actress",
        description: "Velvety British female voice delivers sophistication",
        color: "#ec4899",
        colorEnd: "#db2777",
    },
    {
        id: "matilda",
        name: "Matilda",
        style: "Knowledgeable, Professional",
        description: "A professional woman with a pleasing alto voice",
        color: "#6366f1",
        colorEnd: "#4f46e5",
    },
    {
        id: "nova",
        name: "Nova",
        style: "Warm, Professional",
        description: "Warm and professional with subtle British undertones",
        color: "#ec4899",
        colorEnd: "#db2777",
    },
    {
        id: "onyx",
        name: "Onyx",
        style: "Deep, Authoritative",
        description: "Deep and commanding voice with gravitas",
        color: "#374151",
        colorEnd: "#1f2937",
    },
    {
        id: "shimmer",
        name: "Shimmer",
        style: "Bright, Energetic",
        description: "Youthful and vibrant with infectious energy",
        color: "#fbbf24",
        colorEnd: "#f59e0b",
    },
    {
        id: "echo",
        name: "Echo",
        style: "Wise, Experienced",
        description: "Gravelly wisdom with warmth and depth",
        color: "#6b7280",
        colorEnd: "#4b5563",
    },
    {
        id: "breeze",
        name: "Breeze",
        style: "Soft, Contemplative",
        description: "Gentle and thoughtful with a calming presence",
        color: "#06b6d4",
        colorEnd: "#0891b2",
    },
    {
        id: "alloy",
        name: "Alloy",
        style: "Neutral, Clear",
        description: "Clear and measured, perfect for narration",
        color: "#8b5cf6",
        colorEnd: "#7c3aed",
    },
];
