import z from "zod";

const OverageSchema = z
    .object({
        amount: z.string(),
        currency: z.string(),
    })
    .transform((o) => ({
        amount: o.amount,
        currency: o.currency,
    }));

export const OutputSchema = z
    .object({
        tier: z.string(),
        character_count: z.number(),
        character_limit: z.number(),
        max_character_limit_extension: z.number(),
        max_credit_limit_extension: z.number(),
        can_extend_character_limit: z.boolean(),
        allowed_to_extend_character_limit: z.boolean(),
        next_character_count_reset_unix: z.number(),
        voice_slots_used: z.number(),
        professional_voice_slots_used: z.number(),
        voice_limit: z.number(),
        max_voice_add_edits: z.number(),
        voice_add_edit_counter: z.number(),
        professional_voice_limit: z.number(),
        can_extend_voice_limit: z.boolean(),
        can_use_instant_voice_cloning: z.boolean(),
        can_use_professional_voice_cloning: z.boolean(),
        currency: z.string(),
        current_overage: OverageSchema,
        status: z.string(),
        billing_period: z.string(),
        character_refresh_period: z.string(),
        next_invoice: z.unknown().nullable(),
        open_invoices: z.array(z.unknown()),
        has_open_invoices: z.boolean(),
        pending_change: z.unknown().nullable(),
        has_used_starter_coupon_on_account: z.boolean(),
        has_used_creator_coupon_on_account: z.boolean(),
    })
    .transform((o) => ({
        tier: o.tier,
        characterCount: o.character_count,
        characterLimit: o.character_limit,
        maxCharacterLimitExtension: o.max_character_limit_extension,
        maxCreditLimitExtension: o.max_credit_limit_extension,
        canExtendCharacterLimit: o.can_extend_character_limit,
        allowedToExtendCharacterLimit: o.allowed_to_extend_character_limit,
        nextCharacterCountResetUnix: o.next_character_count_reset_unix,
        voiceSlotsUsed: o.voice_slots_used,
        professionalVoiceSlotsUsed: o.professional_voice_slots_used,
        voiceLimit: o.voice_limit,
        maxVoiceAddEdits: o.max_voice_add_edits,
        voiceAddEditCounter: o.voice_add_edit_counter,
        professionalVoiceLimit: o.professional_voice_limit,
        canExtendVoiceLimit: o.can_extend_voice_limit,
        canUseInstantVoiceCloning: o.can_use_instant_voice_cloning,
        canUseProfessionalVoiceCloning: o.can_use_professional_voice_cloning,
        currency: o.currency,
        currentOverage: o.current_overage,
        status: o.status,
        billingPeriod: o.billing_period,
        characterRefreshPeriod: o.character_refresh_period,
        nextInvoice: o.next_invoice,
        openInvoices: o.open_invoices,
        hasPendingChange: o.pending_change,
        hasOpenInvoices: o.has_open_invoices,
        pendingChange: o.pending_change,
        hasUsedStarterCouponOnAccount: o.has_used_starter_coupon_on_account,
        hasUsedCreatorCouponOnAccount: o.has_used_creator_coupon_on_account,
    }));
