import { z } from "zod";

const TierHistorySchema = z.object({
    items: z.array(z.unknown()),
});

const ModerationSchema = z
    .object({
        enterprise_check_nogo_voice: z.boolean(),
        enterprise_check_block_nogo_voice: z.boolean(),
        never_live_moderate: z.boolean(),
        nogo_voice_similar_voice_upload_count: z.number(),
        enterprise_background_moderation_enabled: z.boolean(),
        safety_status: z.string().nullable(),
        warning_status: z.string().nullable(),
        on_watchlist: z.boolean(),
        is_convai_conversation_live_moderation_enabled: z.boolean(),
        is_convai_custom_llm_with_zrm_allowed: z.boolean(),
        is_agents_custom_llm_with_ivc_allowed: z.boolean(),
        is_ivc_captcha_required: z.boolean(),
        last_updated_timestamp_ms: z.number(),
    })
    .transform(
        ({
            enterprise_check_nogo_voice,
            enterprise_check_block_nogo_voice,
            never_live_moderate,
            nogo_voice_similar_voice_upload_count,
            enterprise_background_moderation_enabled,
            safety_status,
            warning_status,
            on_watchlist,
            is_convai_conversation_live_moderation_enabled,
            is_convai_custom_llm_with_zrm_allowed,
            is_agents_custom_llm_with_ivc_allowed,
            is_ivc_captcha_required,
            last_updated_timestamp_ms,
        }) => ({
            enterpriseCheckNogoVoice: enterprise_check_nogo_voice,
            enterpriseCheckBlockNogoVoice: enterprise_check_block_nogo_voice,
            neverLiveModerate: never_live_moderate,
            nogoVoiceSimilarVoiceUploadCount: nogo_voice_similar_voice_upload_count,
            enterpriseBackgroundModerationEnabled: enterprise_background_moderation_enabled,
            safetyStatus: safety_status,
            warningStatus: warning_status,
            onWatchlist: on_watchlist,
            isConvaiConversationLiveModerationEnabled: is_convai_conversation_live_moderation_enabled,
            isConvaiCustomLLMWithZrmAllowed: is_convai_custom_llm_with_zrm_allowed,
            isAgentsCustomLLMWithIvcAllowed: is_agents_custom_llm_with_ivc_allowed,
            isIvcCaptchaRequired: is_ivc_captcha_required,
            lastUpdatedTimestampMs: last_updated_timestamp_ms,
        }),
    );

const LLMBillingModeSchema = z.object({
    kind: z.string(),
});

const FullSeatMonthlyPriceSchema = z.object({
    amount: z.string(),
    currency: z.string(),
});

const EnterpriseAddonPricesSchema = z
    .object({
        full_seat_monthly_price: FullSeatMonthlyPriceSchema,
    })
    .transform(({ full_seat_monthly_price }) => ({
        fullSeatMonthlyPrice: full_seat_monthly_price,
    }));

const ConvaiFreeAllowanceSchema = z
    .object({
        minutes_used: z.number(),
        minutes_limit: z.number(),
        llm_dollars_used: z.number(),
        llm_dollars_limit: z.number(),
        expires_at_unix: z.number(),
    })
    .transform(({ minutes_used, minutes_limit, llm_dollars_used, llm_dollars_limit, expires_at_unix }) => ({
        minutesUsed: minutes_used,
        minutesLimit: minutes_limit,
        llmDollarsUsed: llm_dollars_used,
        llmDollarsLimit: llm_dollars_limit,
        expiresAtUnix: expires_at_unix,
    }));

const SubscriptionSchema = z
    .object({
        character_limit: z.number(),
        character_count: z.number(),
        character_count_reported: z.number(),
        actual_character_count_reported: z.number(),
        rollover_meter_character_count_reported: z.number(),
        main_meter_character_count_reported: z.number(),
        gift_meter_character_count_reported: z.number(),
        payg_meter_character_count_reported: z.number(),
        tier: z.string(),
        tier_history: TierHistorySchema,
        last_character_limit_reset_unix: z.number(),
        next_character_limit_reset_unix: z.number(),
        can_extend_character_limit: z.boolean(),
        entitled_to_enter_overages: z.boolean(),
        allows_metered_usage: z.boolean(),
        allowed_to_extend_character_limit: z.boolean(),
        voice_limit: z.number(),
        voice_add_edit_counter: z.number(),
        professional_voice_limit: z.number(),
        can_extend_voice_limit: z.boolean(),
        can_use_instant_voice_cloning: z.boolean(),
        can_bypass_voice_captcha: z.boolean(),
        usage_based_price_per_char: z.number().nullable(),
        credits_per_fiat_unit: z.number(),
        extra_pvc_slots: z.number(),
        concurrency: z.number(),
        // custom_model_concurrency: z.record(z.unknown()),
        // custom_concurrency_group_limits: z.record(z.unknown()),
        // extended_group_concurrency: z.record(z.unknown()),
        convai_concurrency: z.number(),
        stt_realtime_concurrency: z.number(),
        stt_batch_concurrency: z.number(),
        priority: z.number(),
        enterprise_music_concurrency: z.number().nullable(),
        music_trial_expiration_unix: z.number().nullable(),
        music_trial_includes_inpainting: z.boolean(),
        content_generation_custom_trial_limit: z.number().nullable(),
        currency: z.string().nullable(),
        can_request_manual_pro_voice_verification: z.boolean(),
        status: z.string(),
        allowed_to_use_projects_api: z.boolean(),
        // plan_character_limit: z.number()
        allowed_to_use_dubbing_api: z.boolean(),
        force_logging_disabled: z.boolean(),
        pci_compliance_required: z.boolean(),
        discounts: z.array(z.unknown()),
        past_discounts: z.unknown().nullable(),
        transfer_characters_to_next_period_count: z.number(),
        moderation: ModerationSchema,
        billing_period: z.string(),
        character_refresh_period: z.string(),
        previously_subscribed_tiers: z.array(z.string()),
        custom_fiat_prices: z.unknown().nullable(),
        // unused_characters_rolled_over_from_previous_period: z.number(),
        // overused_characters_rolled_over_from_previous_period: z.number(),
        // rollover_credits_quota: z.number(),
        // subscription_cycle_credits_quota: z.number(),
        manually_gifted_credits_quota: z.number(),
        // payg_credits_quota: z.number(),
        payg_auto_top_up_config: z.unknown().nullable(),
        pending_midcycle_upsells: z.array(z.unknown()),
        max_character_limit_extension: z.number().nullable(),
        max_credit_limit_extension: z.number(),
        mobile_subscription: z.unknown().nullable(),
        disable_conv_ai_widget_banner: z.boolean(),
        override_conv_ai_widget_link: z.string().nullable(),
        payment_method_last_verified_unix: z.number().nullable(),
        expiry_notification_unix: z.number().nullable(),
        expiry_notification_emails: z.array(z.string()),
        expiry_notification_email_sent_unix: z.number().nullable(),
        consolidated_billing_character_count_reported_from_parent: z.number(),
        consolidated_billing_charge_workspace_id: z.string().nullable(),
        resource_allocations: z.unknown().nullable(),
        workspace_resource_overrides: z.unknown().nullable(),
        grant_approval: z.unknown().nullable(),
        llm_billing_mode: LLMBillingModeSchema,
        created_with_skip_payment_method_collection: z.boolean(),
        unaccepted_terms: z.array(z.unknown()),
        unaccepted_term_ids: z.array(z.unknown()),
        pricing_version: z.string(),
        enterprise_addon_prices: EnterpriseAddonPricesSchema,
        num_months_unused_characters_to_rollover: z.number(),
        custom_rag_limit: z.number().nullable(),
        enterprise_copying_allowed: z.boolean(),
    })
    .transform(
        ({
            character_limit,
            character_count,
            character_count_reported,
            actual_character_count_reported,
            rollover_meter_character_count_reported,
            main_meter_character_count_reported,
            gift_meter_character_count_reported,
            payg_meter_character_count_reported,
            tier_history,
            last_character_limit_reset_unix,
            next_character_limit_reset_unix,
            can_extend_character_limit,
            entitled_to_enter_overages,
            allows_metered_usage,
            allowed_to_extend_character_limit,
            voice_limit,
            voice_add_edit_counter,
            professional_voice_limit,
            can_extend_voice_limit,
            can_use_instant_voice_cloning,
            can_bypass_voice_captcha,
            usage_based_price_per_char,
            credits_per_fiat_unit,
            extra_pvc_slots,
            // custom_model_concurrency,
            // custom_concurrency_group_limits,
            // extended_group_concurrency,
            convai_concurrency,
            stt_realtime_concurrency,
            stt_batch_concurrency,
            enterprise_music_concurrency,
            music_trial_expiration_unix,
            music_trial_includes_inpainting,
            content_generation_custom_trial_limit,
            can_request_manual_pro_voice_verification,
            allowed_to_use_projects_api,
            // plan_character_limit,
            allowed_to_use_dubbing_api,
            force_logging_disabled,
            pci_compliance_required,
            past_discounts,
            transfer_characters_to_next_period_count,
            billing_period,
            character_refresh_period,
            previously_subscribed_tiers,
            custom_fiat_prices,
            // unused_characters_rolled_over_from_previous_period,
            // overused_characters_rolled_over_from_previous_period,
            // rollover_credits_quota,
            // subscription_cycle_credits_quota,
            manually_gifted_credits_quota,
            // payg_credits_quota,
            payg_auto_top_up_config,
            pending_midcycle_upsells,
            max_character_limit_extension,
            max_credit_limit_extension,
            mobile_subscription,
            disable_conv_ai_widget_banner,
            override_conv_ai_widget_link,
            payment_method_last_verified_unix,
            expiry_notification_unix,
            expiry_notification_emails,
            expiry_notification_email_sent_unix,
            consolidated_billing_character_count_reported_from_parent,
            consolidated_billing_charge_workspace_id,
            resource_allocations,
            workspace_resource_overrides,
            grant_approval,
            llm_billing_mode,
            created_with_skip_payment_method_collection,
            unaccepted_terms,
            unaccepted_term_ids,
            pricing_version,
            enterprise_addon_prices,
            num_months_unused_characters_to_rollover,
            custom_rag_limit,
            enterprise_copying_allowed,
            ...rest
        }) => ({
            ...rest,
            characterLimit: character_limit,
            characterCount: character_count,
            characterCountReported: character_count_reported,
            actualCharacterCountReported: actual_character_count_reported,
            rolloverMeterCharacterCountReported: rollover_meter_character_count_reported,
            mainMeterCharacterCountReported: main_meter_character_count_reported,
            giftMeterCharacterCountReported: gift_meter_character_count_reported,
            paygMeterCharacterCountReported: payg_meter_character_count_reported,
            tierHistory: tier_history,
            lastCharacterLimitResetUnix: last_character_limit_reset_unix,
            nextCharacterLimitResetUnix: next_character_limit_reset_unix,
            canExtendCharacterLimit: can_extend_character_limit,
            entitledToEnterOverages: entitled_to_enter_overages,
            allowsMeteredUsage: allows_metered_usage,
            allowedToExtendCharacterLimit: allowed_to_extend_character_limit,
            voiceLimit: voice_limit,
            voiceAddEditCounter: voice_add_edit_counter,
            professionalVoiceLimit: professional_voice_limit,
            canExtendVoiceLimit: can_extend_voice_limit,
            canUseInstantVoiceCloning: can_use_instant_voice_cloning,
            canBypassVoiceCaptcha: can_bypass_voice_captcha,
            usageBasedPricePerChar: usage_based_price_per_char,
            creditsPerFiatUnit: credits_per_fiat_unit,
            extraPvcSlots: extra_pvc_slots,
            // customModelConcurrency: custom_model_concurrency,
            // customConcurrencyGroupLimits: custom_concurrency_group_limits,
            // extendedGroupConcurrency: extended_group_concurrency,
            convaiConcurrency: convai_concurrency,
            sttRealtimeConcurrency: stt_realtime_concurrency,
            sttBatchConcurrency: stt_batch_concurrency,
            enterpriseMusicConcurrency: enterprise_music_concurrency,
            musicTrialExpirationUnix: music_trial_expiration_unix,
            musicTrialIncludesInpainting: music_trial_includes_inpainting,
            contentGenerationCustomTrialLimit: content_generation_custom_trial_limit,
            canRequestManualProVoiceVerification: can_request_manual_pro_voice_verification,
            allowedToUseProjectsAPI: allowed_to_use_projects_api,
            // planCharacterLimit: plan_character_limit,
            allowedToUseDubbingAPI: allowed_to_use_dubbing_api,
            forceLoggingDisabled: force_logging_disabled,
            pciComplianceRequired: pci_compliance_required,
            pastDiscounts: past_discounts,
            transferCharactersToNextPeriodCount: transfer_characters_to_next_period_count,
            billingPeriod: billing_period,
            characterRefreshPeriod: character_refresh_period,
            previouslySubscribedTiers: previously_subscribed_tiers,
            customFiatPrices: custom_fiat_prices,
            // unusedCharactersRolledOverFromPreviousPeriod: unused_characters_rolled_over_from_previous_period,
            // overusedCharactersRolledOverFromPreviousPeriod: overused_characters_rolled_over_from_previous_period,
            // rolloverCreditsQuota: rollover_credits_quota,
            // subscriptionCycleCreditsQuota: subscription_cycle_credits_quota,
            manuallyGiftedCreditsQuota: manually_gifted_credits_quota,
            // paygCreditsQuota: payg_credits_quota,
            paygAutoTopUpConfig: payg_auto_top_up_config,
            pendingMidcycleUpsells: pending_midcycle_upsells,
            maxCharacterLimitExtension: max_character_limit_extension,
            maxCreditLimitExtension: max_credit_limit_extension,
            mobileSubscription: mobile_subscription,
            disableConvAIWidgetBanner: disable_conv_ai_widget_banner,
            overrideConvAIWidgetLink: override_conv_ai_widget_link,
            paymentMethodLastVerifiedUnix: payment_method_last_verified_unix,
            expiryNotificationUnix: expiry_notification_unix,
            expiryNotificationEmails: expiry_notification_emails,
            expiryNotificationEmailSentUnix: expiry_notification_email_sent_unix,
            consolidatedBillingCharacterCountReportedFromParent:
                consolidated_billing_character_count_reported_from_parent,
            consolidatedBillingChargeWorkspaceID: consolidated_billing_charge_workspace_id,
            resourceAllocations: resource_allocations,
            workspaceResourceOverrides: workspace_resource_overrides,
            grantApproval: grant_approval,
            llmBillingMode: llm_billing_mode,
            createdWithSkipPaymentMethodCollection: created_with_skip_payment_method_collection,
            unacceptedTerms: unaccepted_terms,
            unacceptedTermIDs: unaccepted_term_ids,
            pricingVersion: pricing_version,
            enterpriseAddonPrices: enterprise_addon_prices,
            numMonthsUnusedCharactersToRollover: num_months_unused_characters_to_rollover,
            customRagLimit: custom_rag_limit,
            enterpriseCopyingAllowed: enterprise_copying_allowed,
        }),
    );

const IdentityProvidersSchema = z.object({
    google: z.boolean(),
    password: z.boolean(),
    apple: z.boolean(),
    sso: z.boolean(),
});

const SecurityConfigurationSchema = z
    .object({
        identity_providers: IdentityProvidersSchema,
        sso_provider_metadata: z.unknown().nullable(),
    })
    .transform(({ identity_providers, sso_provider_metadata }) => ({
        identityProviders: identity_providers,
        ssoProviderMetadata: sso_provider_metadata,
    }));

const TrainingOptOutSchema = z
    .object({
        timestamp_unix: z.number(),
        training_opt_out: z.boolean(),
    })
    .transform(({ timestamp_unix, training_opt_out }) => ({
        timestampUnix: timestamp_unix,
        trainingOptOut: training_opt_out,
    }));

const StripeCustomerSchema = z.object({
    id: z.string(),
});

const StripeSchema = z
    .object({
        customer: StripeCustomerSchema,
        subscription: z.unknown().nullable(),
        v2_subscription: z.unknown().nullable(),
        subscription_schedule: z.unknown().nullable(),
        subscription_schedule_last_updated: z.unknown().nullable(),
    })
    .transform(({ v2_subscription, subscription_schedule, subscription_schedule_last_updated, ...rest }) => ({
        ...rest,
        v2Subscription: v2_subscription,
        subscriptionSchedule: subscription_schedule,
        subscriptionScheduleLastUpdated: subscription_schedule_last_updated,
    }));

const VoiceLibrarySettingsSchema = z
    .object({
        disable_custom_rates: z.boolean(),
        hide_custom_rates: z.boolean(),
    })
    .transform(({ disable_custom_rates, hide_custom_rates }) => ({
        disableCustomRates: disable_custom_rates,
        hideCustomRates: hide_custom_rates,
    }));

const PromotionsSchema = z
    .object({
        convai_free_allowance: ConvaiFreeAllowanceSchema,
        v3_demo_agent_id: z.string().nullable(),
    })
    .transform(({ convai_free_allowance, v3_demo_agent_id }) => ({
        convaiFreeAllowance: convai_free_allowance,
        v3DemoAgentID: v3_demo_agent_id,
    }));

export const ResponseSchema = z
    .object({
        workspace_id: z.string(),
        name: z.string(),
        storing_shared_files_on_user: z.boolean(),
        subscription: SubscriptionSchema,
        security_configuration: SecurityConfigurationSchema,
        training_opt_out: TrainingOptOutSchema,
        created_at_unix: z.number(),
        owner_id: z.string(),
        stripe: StripeSchema,
        gcp_marketplace_payment_details: z.unknown().nullable(),
        consolidated_billing: z.unknown().nullable(),
        reporting_workspaces: z.array(z.unknown()),
        payouts: z.unknown().nullable(),
        partnerstack_metadata: z.unknown().nullable(),
        vercel_integrations: z.array(z.unknown()),
        previous_refunds: z.array(z.unknown()),
        migration_checkpoint: z.number(),
        payment_methods: z.array(z.unknown()),
        pronunciation_dictionary_locators: z.array(z.unknown()),
        migration_id: z.string().nullable(),
        voice_library_removal_notice_webhook_ids: z.array(z.string()),
        speech_to_text_webhook_ids: z.array(z.string()),
        voice_library_settings: VoiceLibrarySettingsSchema,
        default_resource_access: z.unknown().nullable(),
        usage_display_type: z.string(),
        all_members_permissions: z.array(z.string()),
        all_members_permission_revision: z.string(),
        workspace_permission_overrides: z.unknown().nullable(),
        workspace_permission_overrides_enabled: z.boolean(),
        session_inactivity_timeout: z.number().nullable(),
        user_auto_provisioning: z.unknown().nullable(),
        mfa_required_for_users: z.boolean(),
        batch_calling_terms_accepted: z.boolean(),
        all_members_usage_limit: z.unknown().nullable(),
        scim: z.unknown().nullable(),
        promotions: PromotionsSchema,
        churn_deletion_schedule: z.unknown().nullable(),
        data_retention_confirmation: z.unknown().nullable(),
        consolidated_seats_used: z.number().nullable(),
        max_seats: z.number(),
        max_lite_seats: z.number(),
    })
    .transform(
        ({
            workspace_id,
            storing_shared_files_on_user,
            security_configuration,
            training_opt_out,
            created_at_unix,
            owner_id,
            gcp_marketplace_payment_details,
            consolidated_billing,
            reporting_workspaces,
            partnerstack_metadata,
            vercel_integrations,
            previous_refunds,
            migration_checkpoint,
            payment_methods,
            pronunciation_dictionary_locators,
            migration_id,
            voice_library_removal_notice_webhook_ids,
            speech_to_text_webhook_ids,
            voice_library_settings,
            default_resource_access,
            usage_display_type,
            all_members_permissions,
            all_members_permission_revision,
            workspace_permission_overrides,
            workspace_permission_overrides_enabled,
            session_inactivity_timeout,
            user_auto_provisioning,
            mfa_required_for_users,
            batch_calling_terms_accepted,
            all_members_usage_limit,
            churn_deletion_schedule,
            data_retention_confirmation,
            consolidated_seats_used,
            max_seats,
            max_lite_seats,
            ...rest
        }) => ({
            ...rest,
            workspaceID: workspace_id,
            storingSharedFilesOnUser: storing_shared_files_on_user,
            securityConfiguration: security_configuration,
            trainingOptOut: training_opt_out,
            createdAtUnix: created_at_unix,
            ownerID: owner_id,
            gcpMarketplacePaymentDetails: gcp_marketplace_payment_details,
            consolidatedBilling: consolidated_billing,
            reportingWorkspaces: reporting_workspaces,
            partnerstackMetadata: partnerstack_metadata,
            vercelIntegrations: vercel_integrations,
            previousRefunds: previous_refunds,
            migrationCheckpoint: migration_checkpoint,
            paymentMethods: payment_methods,
            pronunciationDictionaryLocators: pronunciation_dictionary_locators,
            migrationID: migration_id,
            voiceLibraryRemovalNoticeWebhookIDs: voice_library_removal_notice_webhook_ids,
            speechToTextWebhookIDs: speech_to_text_webhook_ids,
            voiceLibrarySettings: voice_library_settings,
            defaultResourceAccess: default_resource_access,
            usageDisplayType: usage_display_type,
            allMembersPermissions: all_members_permissions,
            allMembersPermissionRevision: all_members_permission_revision,
            workspacePermissionOverrides: workspace_permission_overrides,
            workspacePermissionOverridesEnabled: workspace_permission_overrides_enabled,
            sessionInactivityTimeout: session_inactivity_timeout,
            userAutoProvisioning: user_auto_provisioning,
            mfaRequiredForUsers: mfa_required_for_users,
            batchCallingTermsAccepted: batch_calling_terms_accepted,
            allMembersUsageLimit: all_members_usage_limit,
            churnDeletionSchedule: churn_deletion_schedule,
            dataRetentionConfirmation: data_retention_confirmation,
            consolidatedSeatsUsed: consolidated_seats_used,
            maxSeats: max_seats,
            maxLiteSeats: max_lite_seats,
        }),
    );

export type ResponseType = z.output<typeof ResponseSchema>;
