export const LIST_VOICES_ENUMS = {
    CATEGORY: ["GENERATED", "CLONED", "PREMADE", "PROFESSIONAL", "FAMOUS", "HIGH_QUALITY"],
    SORT_BY: ["CREATED_AT_UNIX", "NAME"],
    SORT_DIRECTION: ["ASCENDING", "DESCENDING"],
    VOICE_TYPE: ["PERSONAL", "COMMUNITY", "DEFAULT", "WORKSPACE", "NON_DEFAULT", "SAVED"],
    FINE_TUNING: ["DRAFT", "NOT_VERIFIED", "NOT_STARTED", "QUEUED", "FINE_TUNING", "FINE_TUNED", "FAILED", "DELAYED"],
} as const;
