/*
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
  */

import type React from "react";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Analytics } from "@vercel/analytics/next"
// <Analytics />
// import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header";
// import { AppSidebar } from "@/components/app-sidebar";
import { TypeScriptRPCProvider } from "./tRPCProvider";
import { Toaster } from "@/components/ui/toaster";
// import { SidebarProvider } from "@/components/ui/sidebar";

// const _geist = Geist({ subsets: ["latin"] });
// const _geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "HYPERSONIC",
    description: "Build audiobooks at lightspeed!",
    // generator: "v0.app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="font-sans antialiased">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    themes={["light", "dark", "ocean", "forest", "sunset"]}
                >
                    {/*<SidebarProvider> */}
                    <Header />
                    {/*<AppSidebar /> */}
                    <TypeScriptRPCProvider>
                        <main className="pt-14 flex h-screen w-full">{children}</main>
                    </TypeScriptRPCProvider>
                    <Toaster />
                    {/*</SidebarProvider> */}
                </ThemeProvider>
            </body>
        </html>
    );
}
